#!/bin/bash
#
# Convenience script to setup preferred environment.
#
# This script should be sourced to set the users environment properly.  Check for this:
[[ "${BASH_SOURCE[0]}" = "${0}" ]] && echo "This script should be sourced... like this: \". ${BASH_SOURCE[0]}\""

#
# The "screen" utility uses "Dynamic Prompts" via the "null title-escape-sequence" (ESC k ESC \)
# as part of your prompt.  In RHEL6, there was a bug in /etc/bashrc for PROMPT_COMMAND which is
# fixed in RHEL7.  But now it causes screen titles to be dynamic, so change PROMPT_COMMAND so it
# will just display the username as the screen title:
#
# (this command still needs work because when you are not running screen you see a double prompt
#  with the first line showing the username... comment out for now)
# PROMPT_COMMAND='printf "\033k%s\033\\" "${USER}"'; export PROMPT_COMMAND

#
# Set command prompt to:
#   user@hostname:\path\path
#   $
#
export PS1='\n\u@\h:\w\n\$ '

# Make current directory first on search path
export PATH=.:$PATH

#
# Tweak terminal emulator to support extended characters.
# Ensure your terminal emulator is configured to support UTF8 charset.  For SecureCRT:
# Session Options, Terminal, Appearance, in "Character encoding" dropdown select "UTF-8".
# Then set LC_ALL environment variable:
#
export LC_ALL=en_US.UTF-8

#
# Disable behavior of pasted text always being highlighted.
# Note the if statement is to avoid running the bind command in a non-interactive
# shell.  The special parameter $- lists all active bash options and if it contains
# an "i" option it signifies an interactive shell.
#
if [[ $- = *i* ]]; then
	bind 'set enable-bracketed-paste off'
fi

# -----------------------------------------------------------------------------
# Aliases - General Utility
# -----------------------------------------------------------------------------
alias check='ps -ef | grep -i'
alias ll='ls -lhN'
alias lld="ls -lh | grep '^d'"
alias lldl='ls -lhd */'
alias llf="ls -lh | egrep -v '^d'"
alias lll='echo "Largest 20 files:";ls -l | sort -k5 -n | tail -20'
alias du1='du -h --max-depth=1'
alias du1s='du -h --max-depth=1 | sort --human-numeric-sort'
alias dfl="df -hP"
alias dfnfs="df -hP|grep ":"|sort"
alias check='ps -ef | grep -i'
alias ptree='pstree -Ahp'
alias mon='nmon'
alias tree='tree -A'

# -----------------------------------------------------------------------------
# Functions - General Utility
# -----------------------------------------------------------------------------
#
# Since the "pathmunge" function has never been a standard part of the Linux
# kernel, or a universal command across all distributions, RHEL distros unset
# it in the standard /etc/profile script after their internal use of it.  This
# is so that users do not unknowingly begin calling the pathmunge function in
# their own scripts thinking it is a standard across all Linux flavors.
# However, we like it, so add it back as a properly supported customization
# here in this script.  One caveat though, since this script is itself sourced
# during login by that same /etc/profile script, it means that we cannot use
# the same name "pathmunge" since any function with that name would be unset
# at the end of the login process!  This is why it is named "pathmunge2".
#
pathmunge2 () {
    case ":${PATH}:" in
        *:"$1":*)
            ;;
        *)
            if [ "$2" = "after" ] ; then
                PATH=$PATH:$1
            else
                PATH=$1:$PATH
            fi
    esac
}

